DROP TABLE SALLE CASCADE CONSTRAINT;
DROP TABLE SERVICEH CASCADE CONSTRAINT;
DROP TABLE PATHOLOGIE CASCADE CONSTRAINT;
DROP TABLE PATIENT CASCADE CONSTRAINT;
DROP TABLE PERSONNEL CASCADE CONSTRAINT;
DROP TABLE SOIN CASCADE CONSTRAINT;

DROP TABLE VISITE CASCADE CONSTRAINT;
DROP TABLE INTERVENTION CASCADE CONSTRAINT;
DROP TABLE TELPATIENT CASCADE CONSTRAINT;
DROP TABLE TELPERSONNEL CASCADE CONSTRAINT;
DROP TABLE AFFECTATION CASCADE CONSTRAINT;

CREATE TABLE SERVICEH (
    NUMERO NUMBER(3) NOT NULL,
    NOM VARCHAR(25) NOT NULL,
    NUMTEL VARCHAR(4) NOT NULL,
    CONSTRAINT PK_SERVICEH PRIMARY KEY (NUMERO)
);


CREATE TABLE SALLE (
    NUMERO NUMBER(2) NOT NULL,
    TAUX NUMBER(3) ,
    VOLUME NUMBER(3) NOT NULL,
    NUMSERVICE NUMBER(3) NOT NULL,
    CONSTRAINT PK_SALLE PRIMARY KEY (NUMERO,NUMSERVICE),
    CONSTRAINT FK_SALLE FOREIGN KEY (NUMSERVICE) REFERENCES SERVICEH(NUMERO)
);


CREATE TABLE PATIENT(
    INSEE NUMBER(13) NOT NULL,
    NOM VARCHAR(25)NOT NULL,
    PRENOM VARCHAR(25) NOT NULL,
    CODE_POSTALE NUMBER(5),
    RUE VARCHAR(25),
    VILLE VARCHAR(10),
    NUMERO NUMBER(3), 
    CONSTRAINT PK_PATIENT PRIMARY KEY (INSEE)
);


CREATE TABLE TELPATIENT(
    INSEE NUMBER(13),
    NUMTEL NUMBER(10),
    CONSTRAINT PK_TELPATIENT PRIMARY KEY (INSEE,NUMTEL),
    CONSTRAINT FK_TELPATIENT FOREIGN KEY (INSEE) REFERENCES PATIENT(INSEE)
);

CREATE TABLE PERSONNEL (
    INSEE NUMBER(13),
    SUPERIEUR_INSEE NUMBER(13),
    NOM VARCHAR(20) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    POSTE VARCHAR(20) NOT NULL,
    CODE_POSTALE NUMBER(5),
    RUE VARCHAR(25),
    VILLE VARCHAR(10),
    NUMERO NUMBER(3), 
    CONSTRAINT PK_PERSONNEL PRIMARY KEY (INSEE)

);

CREATE TABLE TELPERSONNEL(
    INSEE NUMBER(13),
    NUMTEL NUMBER(10),
    CONSTRAINT PK_TELPERSONNEL PRIMARY KEY (INSEE,NUMTEL),
    CONSTRAINT FK_TELPERSONNEL FOREIGN KEY (INSEE) REFERENCES PERSONNEL(INSEE)
);



CREATE TABLE AFFECTATION 
(
    INSEE NUMBER(13),
    NUMERO NUMBER(3),
    CONSTRAINT PK_AFFECT PRIMARY KEY (INSEE,NUMERO),
    CONSTRAINT FK_AFFECT FOREIGN KEY (INSEE) REFERENCES PERSONNEL(INSEE),
    CONSTRAINT FK_AFFECT1 FOREIGN KEY (NUMERO) REFERENCES SERVICEH(NUMERO)
);



CREATE TABLE PATHOLOGIE (
    CODE NUMBER(5),
    SCODE NUMBER(3),
    NOM VARCHAR(50),
    CONSTRAINT PK_PATHOLOGIE PRIMARY KEY (CODE),
    CONSTRAINT FK_P1 FOREIGN KEY (SCODE) REFERENCES SERVICEH(NUMERO)
);


CREATE TABLE SOIN(
    NOM VARCHAR(25),
    CODE_P NUMBER(5),
    COÛT NUMBER(10),
    CONSTRAINT PK_SOIN PRIMARY KEY (NOM,COÛT),
    CONSTRAINT FK_SOIN FOREIGN KEY (CODE_P) REFERENCES PATHOLOGIE(CODE)
);


CREATE TABLE VISITE (
    DATE_A DATE NOT NULL,
    DATE_S DATE NOT NULL, 
    INSEE_PA NUMBER(13),
    PCODE NUMBER(5),
    CONSTRAINT FK_V FOREIGN KEY (INSEE_PA) REFERENCES PATIENT(INSEE),
    CONSTRAINT FK_V2 FOREIGN KEY (PCODE) REFERENCES PATHOLOGIE(CODE),
    CONSTRAINT PK_V PRIMARY KEY (DATE_A,DATE_S,INSEE_PA,PCODE)
);


CREATE TABLE INTERVENTION (
    PA_INSEE NUMBER(13),
    POSTE VARCHAR(20) CHECK( POSTE IN ('MEDECIN')),
    SNOM VARCHAR(25),
    CSALLE NUMBER(3),
    CNUMSERVICE NUMBER(3),
    PE_INSEE NUMBER(13),
    I_DATE DATE NOT NULL,
    SCOÛT NUMBER(5) NOT NULL,

    RESULTAT VARCHAR(7) CHECK( RESULTAT IN ('NEGATIF' , 'POSITIF')),
    CONSTRAINT FK_INTERVENTION2 FOREIGN KEY (PA_INSEE) REFERENCES PATIENT(INSEE),
    CONSTRAINT FK_ISSP1 FOREIGN KEY (PE_INSEE) REFERENCES PERSONNEL(INSEE),
    CONSTRAINT FK_ISSP2 FOREIGN KEY (SNOM,SCOÛT) REFERENCES SOIN(NOM,COÛT),
    CONSTRAINT FK_ISSP3 FOREIGN KEY (CSALLE,CNUMSERVICE) REFERENCES SALLE(NUMERO,NUMSERVICE),
    CONSTRAINT PK_INTERVENTION PRIMARY KEY (PA_INSEE,SNOM,CSALLE,CNUMSERVICE,PE_INSEE) 
);